In [1]:
import numpy as np
data=np.load("sample_data/1021_1-0.npz")

In [2]:
print(data.files)

['t', 'pos', 'idcs_airfoil', 'pressure', 'velocity_in', 'velocity_out']


In [4]:
print(type(data))

<class 'numpy.lib.npyio.NpzFile'>


In [5]:
arr={}
for key in data.files:
    arr[key]=data[key]

In [8]:
print(arr["pos"])

[[ 1.6569071   0.09583618  0.75      ]
 [ 1.7194145   0.00208382  0.62499726]
 [ 1.6262949  -0.06177336  0.6868285 ]
 ...
 [ 0.8265631   0.00829163  0.13717332]
 [ 0.81320083  0.02713627  0.12096836]
 [ 0.8183516   0.0127282   0.12978129]]
